### ISSUE TITLE
Composer can't find ext-geoip

### ISSUE THREAD

**Issue by kitsunde** [g4code/geoip#1]
Problem 1
    - Installation request for g4/geoip dev-master -> satisfiable by g4/geoip[dev-master].
    - g4/geoip dev-master requires ext-geoip \* -> the requested PHP extension geoip is missing from your system.

**Comment by dsamardzija** [comment]
You need to have GeoIP PHP extension installed on the system for this

more info here:
http://php.net/manual/en/book.geoip.php

installation:
http://php.net/manual/en/geoip.setup.php
